# fly.toml app configuration file generated for wedding-gallery-complete-copia-hidden-sun-5743 on 2025-04-08T19:36:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wedding-gallery-complete-copia-hidden-sun-5743'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
